// src/app/layout.tsx (✅ SERVER COMPONENT — no "use client")

import './globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
import type { Metadata } from 'next';
import { ClientLayoutWrapper } from '@/components/ClientLayoutWrapper'; // 👈 new wrapper
import  AppFooter  from '@/components/AppFooter';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      
        <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
        <AppFooter />
      </body>
    </html>
  );
}
